name: devops GPT

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python --version
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        echo "OPENAI_API_KEY value is: $OPENAI_API_KEY"
        pytest -v
        pytest  --maxfail=1 --disable-warnings -v > result.log; tail -n 10 result.log

    - name: Analyze CI log with GPT Assistant
      run: |
        echo "OPENAI_API_KEY value is: $OPENAI_API_KEY"
        python log_analyze.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
