name: devops GPT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest > result.log; tail -n 10 result.log

    - name: Analyze CI log with GPT Assistant
      run: |
        python ci_log_analyzer.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
