name: Check Timeout vs Script Failure
on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Run your script
        id: run_script
        run: |
          echo "Running the script..."
          # Simulate failure or long-running (uncomment one to test)
          # exit 1           # simulate script failure
           sleep 700         # simulate timeout (longer than 10 minutes)

      - name: Job failed (script error)
        if: failure() && !cancelled()
        run: echo "❌ Job failed due to script error."

      - name: Job cancelled (timeout)
        if: cancelled()
        run: echo "⏱️ Job was cancelled (likely timeout)."

      - name: Job succeeded
        if: success()
        run: echo "✅ Job succeeded."
